export default {
  '/': 'sound & visual artist',
  '/paintings/2019': 'Paintings, 2019',
  '/paintings/delta-s': 'ΔS',
  '/performance/send-and-receive-2021': 'Send + Receive, 2021',
  '/photographs/blackwhite': 'Blackwhite',
  '/photographs/heir': 'Heir',
  '/photographs/images-pour-rien': 'Images Pour Rien',
  '/photographs/locus': 'Locus',
  '/photographs/northern-italy': 'Northern Italy',
  '/photographs/protest': 'Protest',
  '/sound/a-certain-point-of-inertia': 'A Certain Point of Intertia',
  '/sound/a-pattern-of-extraction': 'A Pattern of Extraction',
  '/sound/a-recasting-of-indices': 'A Recasting of Indices',
  '/sound/a-stable-means-of-degradation': 'A Stable Means of Degradation',
  '/sound/enfold': 'Enfold: Rehearsal for Send + Receive, 2021',
  '/sound/four-unbindings': 'Four Unbindings',
  '/sound/presque-tout': 'London (UK), 07/06/2014, Evening',
  '/sound/traces-blurs-signs': 'Traces Blurs Signs',
  '/biography': 'Biography',
  '/contact': 'Contact',
}
